/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { KJGenesisFunderKey } from './KJGenesisFunderKey.js';
export * as factories from './factories/index.js';
export { KJGenesisFunderKey__factory } from './factories/KJGenesisFunderKey__factory.js';