/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface KJGenesisFunderKeyInterface extends Interface {
    getFunction(nameOrSignature: "MAX_SECONDARY_ROYALTY_BPS" | "MAX_SUPPLY" | "acceptOwnership" | "allocate" | "allowlistMint" | "allowlistRoot" | "approve" | "artProvenanceHash" | "balanceOf" | "contractURI" | "freezeMetadata" | "getApproved" | "isApprovedForAll" | "isFunder" | "maxPerWallet" | "metadataFrozen" | "mintPrice" | "mintedByWallet" | "name" | "owner" | "ownerOf" | "pause" | "paused" | "pendingOwner" | "publicMint" | "remainingSupply" | "renounceOwnership" | "reveal" | "revealed" | "royaltyInfo" | "safeTransferFrom(address,address,uint256)" | "safeTransferFrom(address,address,uint256,bytes)" | "salePhase" | "setAllowlistRoot" | "setApprovalForAll" | "setSalePhase" | "setUnrevealedTokenURI" | "supportsInterface" | "symbol" | "tokenURI" | "totalSupply" | "transferFrom" | "transferOwnership" | "treasury" | "unpause" | "unrevealedTokenURI" | "withdraw"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AllowlistRootUpdated" | "Approval" | "ApprovalForAll" | "MetadataFrozen" | "MetadataRevealed" | "OwnershipTransferStarted" | "OwnershipTransferred" | "Paused" | "SalePhaseUpdated" | "Transfer" | "TreasuryWithdrawal" | "Unpaused" | "UnrevealedURIUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'MAX_SECONDARY_ROYALTY_BPS', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_SUPPLY', values?: undefined): string;
encodeFunctionData(functionFragment: 'acceptOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'allocate', values: [AddressLike[]]): string;
encodeFunctionData(functionFragment: 'allowlistMint', values: [BigNumberish, BigNumberish, BytesLike[]]): string;
encodeFunctionData(functionFragment: 'allowlistRoot', values?: undefined): string;
encodeFunctionData(functionFragment: 'approve', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'artProvenanceHash', values?: undefined): string;
encodeFunctionData(functionFragment: 'balanceOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'contractURI', values?: undefined): string;
encodeFunctionData(functionFragment: 'freezeMetadata', values?: undefined): string;
encodeFunctionData(functionFragment: 'getApproved', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'isApprovedForAll', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'isFunder', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'maxPerWallet', values?: undefined): string;
encodeFunctionData(functionFragment: 'metadataFrozen', values?: undefined): string;
encodeFunctionData(functionFragment: 'mintPrice', values?: undefined): string;
encodeFunctionData(functionFragment: 'mintedByWallet', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'name', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'ownerOf', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'pause', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'pendingOwner', values?: undefined): string;
encodeFunctionData(functionFragment: 'publicMint', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'remainingSupply', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'reveal', values: [string, string]): string;
encodeFunctionData(functionFragment: 'revealed', values?: undefined): string;
encodeFunctionData(functionFragment: 'royaltyInfo', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'safeTransferFrom(address,address,uint256)', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'safeTransferFrom(address,address,uint256,bytes)', values: [AddressLike, AddressLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'salePhase', values?: undefined): string;
encodeFunctionData(functionFragment: 'setAllowlistRoot', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'setApprovalForAll', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'setSalePhase', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setUnrevealedTokenURI', values: [string]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'symbol', values?: undefined): string;
encodeFunctionData(functionFragment: 'tokenURI', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'totalSupply', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferFrom', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'treasury', values?: undefined): string;
encodeFunctionData(functionFragment: 'unpause', values?: undefined): string;
encodeFunctionData(functionFragment: 'unrevealedTokenURI', values?: undefined): string;
encodeFunctionData(functionFragment: 'withdraw', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'MAX_SECONDARY_ROYALTY_BPS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_SUPPLY', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'acceptOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'allocate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'allowlistMint', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'allowlistRoot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approve', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'artProvenanceHash', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'balanceOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'contractURI', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'freezeMetadata', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getApproved', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isApprovedForAll', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isFunder', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'maxPerWallet', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'metadataFrozen', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mintPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mintedByWallet', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'name', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ownerOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pendingOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'publicMint', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'remainingSupply', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reveal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revealed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'royaltyInfo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'safeTransferFrom(address,address,uint256)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'safeTransferFrom(address,address,uint256,bytes)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'salePhase', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setAllowlistRoot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setApprovalForAll', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setSalePhase', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setUnrevealedTokenURI', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'symbol', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tokenURI', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalSupply', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferFrom', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'treasury', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unrevealedTokenURI', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
  }

  
    export namespace AllowlistRootUpdatedEvent {
      export type InputTuple = [root: BytesLike];
      export type OutputTuple = [root: string];
      export interface OutputObject {root: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ApprovalEvent {
      export type InputTuple = [owner: AddressLike, approved: AddressLike, tokenId: BigNumberish];
      export type OutputTuple = [owner: string, approved: string, tokenId: bigint];
      export interface OutputObject {owner: string, approved: string, tokenId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ApprovalForAllEvent {
      export type InputTuple = [owner: AddressLike, operator: AddressLike, approved: boolean];
      export type OutputTuple = [owner: string, operator: string, approved: boolean];
      export interface OutputObject {owner: string, operator: string, approved: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MetadataFrozenEvent {
      export type InputTuple = [baseURI: string, contractURI: string];
      export type OutputTuple = [baseURI: string, contractURI: string];
      export interface OutputObject {baseURI: string, contractURI: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MetadataRevealedEvent {
      export type InputTuple = [baseURI: string, contractURI: string];
      export type OutputTuple = [baseURI: string, contractURI: string];
      export interface OutputObject {baseURI: string, contractURI: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferStartedEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SalePhaseUpdatedEvent {
      export type InputTuple = [previousPhase: BigNumberish, newPhase: BigNumberish];
      export type OutputTuple = [previousPhase: bigint, newPhase: bigint];
      export interface OutputObject {previousPhase: bigint, newPhase: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferEvent {
      export type InputTuple = [from: AddressLike, to: AddressLike, tokenId: BigNumberish];
      export type OutputTuple = [from: string, to: string, tokenId: bigint];
      export interface OutputObject {from: string, to: string, tokenId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TreasuryWithdrawalEvent {
      export type InputTuple = [treasury: AddressLike, amount: BigNumberish];
      export type OutputTuple = [treasury: string, amount: bigint];
      export interface OutputObject {treasury: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnrevealedURIUpdatedEvent {
      export type InputTuple = [uri: string];
      export type OutputTuple = [uri: string];
      export interface OutputObject {uri: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface KJGenesisFunderKey extends BaseContract {
    
    connect(runner?: ContractRunner | null): KJGenesisFunderKey;
    waitForDeployment(): Promise<this>;

    interface: KJGenesisFunderKeyInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    MAX_SECONDARY_ROYALTY_BPS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_SUPPLY: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    acceptOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    allocate: TypedContractMethod<
      [recipients: AddressLike[], ],
      [void],
      'nonpayable'
    >
    

    
    allowlistMint: TypedContractMethod<
      [quantity: BigNumberish, allocation: BigNumberish, proof: BytesLike[], ],
      [void],
      'payable'
    >
    

    
    allowlistRoot: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    approve: TypedContractMethod<
      [to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    artProvenanceHash: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    balanceOf: TypedContractMethod<
      [owner: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    contractURI: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    freezeMetadata: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    getApproved: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    isApprovedForAll: TypedContractMethod<
      [owner: AddressLike, operator: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isFunder: TypedContractMethod<
      [account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    maxPerWallet: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    metadataFrozen: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    mintPrice: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    mintedByWallet: TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    name: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    ownerOf: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    pause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    pendingOwner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    publicMint: TypedContractMethod<
      [quantity: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    remainingSupply: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    reveal: TypedContractMethod<
      [baseURI_: string, contractURI_: string, ],
      [void],
      'nonpayable'
    >
    

    
    revealed: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    royaltyInfo: TypedContractMethod<
      [tokenId: BigNumberish, salePrice: BigNumberish, ],
      [[string, bigint] & {receiver: string, amount: bigint }],
      'view'
    >
    

    
    "safeTransferFrom(address,address,uint256)": TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    "safeTransferFrom(address,address,uint256,bytes)": TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, data: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    salePhase: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    setAllowlistRoot: TypedContractMethod<
      [root: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    setApprovalForAll: TypedContractMethod<
      [operator: AddressLike, approved: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setSalePhase: TypedContractMethod<
      [newPhase: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setUnrevealedTokenURI: TypedContractMethod<
      [uri: string, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    symbol: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    tokenURI: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    totalSupply: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferFrom: TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    treasury: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    unpause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    unrevealedTokenURI: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    withdraw: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'MAX_SECONDARY_ROYALTY_BPS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_SUPPLY'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'acceptOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'allocate'): TypedContractMethod<
      [recipients: AddressLike[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'allowlistMint'): TypedContractMethod<
      [quantity: BigNumberish, allocation: BigNumberish, proof: BytesLike[], ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'allowlistRoot'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'approve'): TypedContractMethod<
      [to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'artProvenanceHash'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'balanceOf'): TypedContractMethod<
      [owner: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'contractURI'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'freezeMetadata'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getApproved'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'isApprovedForAll'): TypedContractMethod<
      [owner: AddressLike, operator: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isFunder'): TypedContractMethod<
      [account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'maxPerWallet'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'metadataFrozen'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'mintPrice'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'mintedByWallet'): TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'name'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'ownerOf'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'pendingOwner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'publicMint'): TypedContractMethod<
      [quantity: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'remainingSupply'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'reveal'): TypedContractMethod<
      [baseURI_: string, contractURI_: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revealed'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'royaltyInfo'): TypedContractMethod<
      [tokenId: BigNumberish, salePrice: BigNumberish, ],
      [[string, bigint] & {receiver: string, amount: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'safeTransferFrom(address,address,uint256)'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'safeTransferFrom(address,address,uint256,bytes)'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, data: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'salePhase'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'setAllowlistRoot'): TypedContractMethod<
      [root: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setApprovalForAll'): TypedContractMethod<
      [operator: AddressLike, approved: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setSalePhase'): TypedContractMethod<
      [newPhase: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setUnrevealedTokenURI'): TypedContractMethod<
      [uri: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'symbol'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'tokenURI'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'totalSupply'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferFrom'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'treasury'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'unpause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unrevealedTokenURI'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AllowlistRootUpdated'): TypedContractEvent<AllowlistRootUpdatedEvent.InputTuple, AllowlistRootUpdatedEvent.OutputTuple, AllowlistRootUpdatedEvent.OutputObject>;
getEvent(key: 'Approval'): TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
getEvent(key: 'ApprovalForAll'): TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
getEvent(key: 'MetadataFrozen'): TypedContractEvent<MetadataFrozenEvent.InputTuple, MetadataFrozenEvent.OutputTuple, MetadataFrozenEvent.OutputObject>;
getEvent(key: 'MetadataRevealed'): TypedContractEvent<MetadataRevealedEvent.InputTuple, MetadataRevealedEvent.OutputTuple, MetadataRevealedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferStarted'): TypedContractEvent<OwnershipTransferStartedEvent.InputTuple, OwnershipTransferStartedEvent.OutputTuple, OwnershipTransferStartedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'SalePhaseUpdated'): TypedContractEvent<SalePhaseUpdatedEvent.InputTuple, SalePhaseUpdatedEvent.OutputTuple, SalePhaseUpdatedEvent.OutputObject>;
getEvent(key: 'Transfer'): TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
getEvent(key: 'TreasuryWithdrawal'): TypedContractEvent<TreasuryWithdrawalEvent.InputTuple, TreasuryWithdrawalEvent.OutputTuple, TreasuryWithdrawalEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
getEvent(key: 'UnrevealedURIUpdated'): TypedContractEvent<UnrevealedURIUpdatedEvent.InputTuple, UnrevealedURIUpdatedEvent.OutputTuple, UnrevealedURIUpdatedEvent.OutputObject>;

    filters: {
      
      'AllowlistRootUpdated(bytes32)': TypedContractEvent<AllowlistRootUpdatedEvent.InputTuple, AllowlistRootUpdatedEvent.OutputTuple, AllowlistRootUpdatedEvent.OutputObject>;
      AllowlistRootUpdated: TypedContractEvent<AllowlistRootUpdatedEvent.InputTuple, AllowlistRootUpdatedEvent.OutputTuple, AllowlistRootUpdatedEvent.OutputObject>;
    

      'Approval(address,address,uint256)': TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
      Approval: TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
    

      'ApprovalForAll(address,address,bool)': TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
      ApprovalForAll: TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
    

      'MetadataFrozen(string,string)': TypedContractEvent<MetadataFrozenEvent.InputTuple, MetadataFrozenEvent.OutputTuple, MetadataFrozenEvent.OutputObject>;
      MetadataFrozen: TypedContractEvent<MetadataFrozenEvent.InputTuple, MetadataFrozenEvent.OutputTuple, MetadataFrozenEvent.OutputObject>;
    

      'MetadataRevealed(string,string)': TypedContractEvent<MetadataRevealedEvent.InputTuple, MetadataRevealedEvent.OutputTuple, MetadataRevealedEvent.OutputObject>;
      MetadataRevealed: TypedContractEvent<MetadataRevealedEvent.InputTuple, MetadataRevealedEvent.OutputTuple, MetadataRevealedEvent.OutputObject>;
    

      'OwnershipTransferStarted(address,address)': TypedContractEvent<OwnershipTransferStartedEvent.InputTuple, OwnershipTransferStartedEvent.OutputTuple, OwnershipTransferStartedEvent.OutputObject>;
      OwnershipTransferStarted: TypedContractEvent<OwnershipTransferStartedEvent.InputTuple, OwnershipTransferStartedEvent.OutputTuple, OwnershipTransferStartedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'SalePhaseUpdated(uint8,uint8)': TypedContractEvent<SalePhaseUpdatedEvent.InputTuple, SalePhaseUpdatedEvent.OutputTuple, SalePhaseUpdatedEvent.OutputObject>;
      SalePhaseUpdated: TypedContractEvent<SalePhaseUpdatedEvent.InputTuple, SalePhaseUpdatedEvent.OutputTuple, SalePhaseUpdatedEvent.OutputObject>;
    

      'Transfer(address,address,uint256)': TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
      Transfer: TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
    

      'TreasuryWithdrawal(address,uint256)': TypedContractEvent<TreasuryWithdrawalEvent.InputTuple, TreasuryWithdrawalEvent.OutputTuple, TreasuryWithdrawalEvent.OutputObject>;
      TreasuryWithdrawal: TypedContractEvent<TreasuryWithdrawalEvent.InputTuple, TreasuryWithdrawalEvent.OutputTuple, TreasuryWithdrawalEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    

      'UnrevealedURIUpdated(string)': TypedContractEvent<UnrevealedURIUpdatedEvent.InputTuple, UnrevealedURIUpdatedEvent.OutputTuple, UnrevealedURIUpdatedEvent.OutputObject>;
      UnrevealedURIUpdated: TypedContractEvent<UnrevealedURIUpdatedEvent.InputTuple, UnrevealedURIUpdatedEvent.OutputTuple, UnrevealedURIUpdatedEvent.OutputObject>;
    
    };
  }